name: DemoPipeline_$(Date:YYYYMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
  pool:
    name: 'Default'
  steps:
    - checkout: self
      persistCredentials: true
    - script: echo "Hello World!"
      displayName: 'Run a one-line script'
  

