
trigger:
  - main
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Building the project...
            displayName: 'Build Step'

