name: DemoPipeline_$(Date:YYYYMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
          - script: echo Building the project...
            displayName: 'Build Step'
  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: Deploy Job
        steps:
          - script: echo Deploying the project...
            displayName: 'Deploy Step'

